'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,CheckCircle2,X} from 'lucide-react';

const initial={fullName:'',email:'',company:'',stage:'',problem:'',budget:'',timeline:''};
export default function ContactModal({isOpen,onClose}){const[form,setForm]=useState(initial),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(!isOpen)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old}},[isOpen]);
 if(!isOpen)return null;
 const update=e=>setForm(v=>({...v,[e.target.name]:e.target.value}));
 const submit=async e=>{e.preventDefault();setLoading(true);setMessage('');try{const objective=[`Stage: ${form.stage}`,`Problem: ${form.problem}`,form.budget&&`Budget: ${form.budget}`,form.timeline&&`Timeline: ${form.timeline}`].filter(Boolean).join('\n');const res=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fullName:form.fullName,email:form.email,company:form.company,objective})});const out=await res.json();if(!res.ok)throw new Error(out.message);setMessage('Project brief received. A WRONYX specialist will contact you with the next step.');setForm(initial)}catch(err){setMessage(err.message||'We could not send your brief. Please try again.')}finally{setLoading(false)}};
 return <div className="project-brief-overlay" role="dialog" aria-modal="true" aria-labelledby="project-title" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="project-brief-shell"><button className="brief-close" onClick={onClose} aria-label="Close project brief"><X/></button><aside><p>START A PROJECT / WRONYX</p><h2 id="project-title">Bring us the problem<br/><em>worth solving.</em></h2><span>Tell us what is changing, what is getting in the way, and where you want the product to go. We will come back with a clear next step.</span><div><b>What happens next</b><ol><li><i>01</i>We review your brief</li><li><i>02</i>A specialist contacts you</li><li><i>03</i>You receive a focused plan</li></ol></div><a href="mailto:global.business@wronyx.com">global.business@wronyx.com <ArrowUpRight/></a></aside><form onSubmit={submit} autoComplete="on"><div className="brief-grid"><label>Your name *<input required autoFocus name="fullName" value={form.fullName} onChange={update} autoComplete="name" placeholder="Full name"/></label><label>Work email *<input required type="email" name="email" value={form.email} onChange={update} autoComplete="email" placeholder="you@company.com"/></label><label>Company *<input required name="company" value={form.company} onChange={update} autoComplete="organization" placeholder="Company name"/></label><label>Project stage *<select required name="stage" value={form.stage} onChange={update}><option value="">Select one</option><option>Exploring an idea</option><option>Planning and validation</option><option>Ready to build</option><option>Scaling an existing product</option><option>Modernizing a legacy platform</option></select></label><label className="brief-wide">What are we solving? *<textarea required name="problem" value={form.problem} onChange={update} rows="5" placeholder="The problem, the opportunity, and what success looks like…"/></label><label>Estimated investment<select name="budget" value={form.budget} onChange={update}><option value="">Not decided yet</option><option>$25k – $75k</option><option>$75k – $150k</option><option>$150k – $300k</option><option>$300k+</option></select></label><label>Ideal timeline<select name="timeline" value={form.timeline} onChange={update}><option value="">Flexible</option><option>Within 1 month</option><option>1 – 3 months</option><option>3 – 6 months</option><option>6+ months</option></select></label></div>{message&&<p className="brief-message"><CheckCircle2/>{message}</p>}<footer><span>By submitting, you agree to be contacted about this project.</span><button disabled={loading}>{loading?'Sending brief…':'Send project brief'} <ArrowUpRight/></button></footer></form></div></div>}
