'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,Briefcase,Clock,MapPin,Upload,FileText,CheckCircle2,Sparkles,Save,Trash2} from 'lucide-react';
import WronyxLogo from './WronyxLogo';

const responsibilities=['Design and deploy scalable AI and machine learning solutions for production use','Build and optimize LLM, NLP, or computer vision models for business needs','Collaborate with product and engineering teams to integrate AI features','Develop data pipelines, model evaluation frameworks, and monitoring processes','Mentor junior engineers and drive AI best practices across the team'];
const requirements=['Degree in Computer Science, Data Science, Software Engineering, or a closely related field.','4+ years of experience developing, deploying, and optimizing machine learning models and AI algorithms in production environments.','Strong proficiency in Python, Java, or Scala, with TensorFlow, PyTorch, or scikit-learn.','Hands-on experience with AWS, Azure, or GCP; familiarity with Spark, Kafka, or Hadoop.','Experience with SQL or NoSQL databases, data warehouses, ETL tooling, and orchestration frameworks such as Apache Airflow.','Professional English proficiency for client communication.','Experience mentoring and leading junior team members is a plus.'];
const empty={firstName:'',lastName:'',email:'',phone:'',address:'',linkedin:'',portfolio:'',experience:'',technologies:'',dataEngineering:'',summary:'',coverLetter:'',onsite:''};
export default function JobApplication(){const[tab,setTab]=useState('overview'),[form,setForm]=useState(empty),[resume,setResume]=useState(null),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),fileRef=useRef(null);
 useEffect(()=>{try{const saved=localStorage.getItem('wronyx-career-draft');if(saved)setForm({...empty,...JSON.parse(saved)})}catch{}},[]);
 const update=e=>setForm(v=>({...v,[e.target.name]:e.target.value}));
 const saveDraft=()=>{localStorage.setItem('wronyx-career-draft',JSON.stringify(form));setStatus('Draft saved on this device.');};
 const clear=()=>{setForm(empty);setResume(null);localStorage.removeItem('wronyx-career-draft');setStatus('Draft cleared.');};
 const importResume=async e=>{const file=e.target.files?.[0];if(!file)return;setResume(file);setStatus(`${file.name} attached.`);if(file.type==='text/plain'){const text=await file.text();const email=text.match(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/)?.[0];const phone=text.match(/(?:\+?\d[\d\s()-]{7,}\d)/)?.[0];const firstLine=text.split(/\r?\n/).find(x=>x.trim().split(/\s+/).length<=4)?.trim();const parts=(firstLine||'').split(/\s+/);setForm(v=>({...v,email:email||v.email,phone:phone||v.phone,firstName:parts[0]||v.firstName,lastName:parts.slice(1).join(' ')||v.lastName,technologies:v.technologies||text.match(/(?:Python|PyTorch|TensorFlow|scikit-learn|AWS|Azure|GCP|Spark|Kafka|Airflow|SQL|NLP|LLM)/gi)?.join(', ')||''}));setStatus('Resume imported and matching fields were autofilled.');}};
 const submit=async e=>{e.preventDefault();setBusy(true);setStatus('');try{const data=new FormData();Object.entries(form).forEach(([k,v])=>data.append(k,v));data.append('jobTitle','Senior AI Engineer');if(resume)data.append('resume',resume);const res=await fetch('/api/applications',{method:'POST',body:data});const out=await res.json();if(!res.ok)throw new Error(out.message);localStorage.removeItem('wronyx-career-draft');setStatus('Application received. Our talent team will review your profile.');}catch(err){setStatus(err.message||'Application could not be submitted.');}finally{setBusy(false)}};
 return <main className="job-page"><header className="job-top"><Link href="/careers"><ArrowLeft/> All careers</Link><WronyxLogo size="lg"/><span>WRONYX TALENT</span></header>
 <section className="job-intro"><p>AI ENGINEERING / LAHORE</p><h1>Senior AI Engineer</h1><div><span><MapPin/>Lahore, Pakistan</span><span><Briefcase/>On-site · Cluster Head</span><span><Clock/>Full time</span></div></section>
 <nav className="job-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Overview</button><button className={tab==='application'?'active':''} onClick={()=>setTab('application')}>Application</button></nav>
 {tab==='overview'?<section className="job-overview"><article><h2>Description</h2><p>WRONYX is a service-based technology company operating globally across the Information Technology and Services industry. We help businesses solve complex challenges through practical, scalable digital solutions with a focus on reliable outcomes in real-world production environments.</p><p>As a Senior AI Engineer, you will shape and deliver AI solutions for meaningful business use cases—turning advanced machine learning concepts into production-ready systems and partnering with cross-functional teams to bring intelligence into products and platforms.</p><h2>Responsibilities</h2><ul>{responsibilities.map(x=><li key={x}>{x}</li>)}</ul><h2>Requirements</h2><ul>{requirements.map(x=><li key={x}>{x}</li>)}</ul></article><aside><div><small>ROLE</small><b>Senior AI Engineer</b></div><div><small>WORKPLACE</small><b>On-site, Lahore</b></div><div><small>EMPLOYMENT</small><b>Full time</b></div><button onClick={()=>setTab('application')}>Apply for this role</button></aside></section>:<form className="application-form" onSubmit={submit} autoComplete="on"><section className="resume-import"><div><Sparkles/><span><b>Autofill application</b><small>Import a résumé. TXT files can populate matching fields automatically; PDF and DOCX files are attached for review.</small></span></div><button type="button" onClick={()=>fileRef.current?.click()}><Upload/> Import résumé</button><input ref={fileRef} type="file" accept=".pdf,.doc,.docx,.txt,.rtf" onChange={importResume}/>{resume&&<p><FileText/> {resume.name}</p>}</section>
 <div className="form-actions"><span>* Required fields</span><div><button type="button" onClick={saveDraft}><Save/> Save draft</button><button type="button" onClick={clear}><Trash2/> Clear</button></div></div>
 <fieldset><legend>Personal information</legend><div className="form-grid"><label>First name *<input required name="firstName" value={form.firstName} onChange={update} autoComplete="given-name"/></label><label>Last name *<input required name="lastName" value={form.lastName} onChange={update} autoComplete="family-name"/></label><label className="wide">Email *<input required type="email" name="email" value={form.email} onChange={update} autoComplete="email"/></label><label>Phone *<input required type="tel" name="phone" value={form.phone} onChange={update} autoComplete="tel"/></label><label>City, region and country *<input required name="address" value={form.address} onChange={update} autoComplete="address-level2"/></label><label>LinkedIn profile<input type="url" name="linkedin" value={form.linkedin} onChange={update} autoComplete="url"/></label><label>Portfolio / GitHub<input type="url" name="portfolio" value={form.portfolio} onChange={update}/></label></div></fieldset>
 <fieldset><legend>Your profile</legend><label>Professional summary<textarea name="summary" value={form.summary} onChange={update} rows="4"/></label><label>Years of AI engineering experience *<input required name="experience" value={form.experience} onChange={update} inputMode="numeric" placeholder="e.g. 5 years"/></label><label>Technologies you have worked with *<textarea required name="technologies" value={form.technologies} onChange={update} rows="4" placeholder="Python, PyTorch, TensorFlow, LLMs, AWS…"/></label><label>Data engineering experience *<textarea required name="dataEngineering" value={form.dataEngineering} onChange={update} rows="4"/></label><label>Cover letter<textarea name="coverLetter" value={form.coverLetter} onChange={update} rows="6"/></label><label>Are you comfortable with a full-time, on-site Lahore role? *<select required name="onsite" value={form.onsite} onChange={update}><option value="">Select an answer</option><option value="yes">Yes</option><option value="no">No</option></select></label></fieldset>
 <button className="submit-application" disabled={busy}>{busy?'Submitting…':'Submit application'}</button>{status&&<p className="application-status"><CheckCircle2/>{status}</p>}</form>}
 </main>}
