'use client';
import {useState} from 'react';
import {ArrowRight,Building2,Factory,HeartPulse,Landmark,Plane,Rocket,ShieldCheck,ShoppingBag,Sparkles,TrendingUp,Users} from 'lucide-react';
import Navbar from './Navbar';import Footer from './Footer';import ContactModal from './ContactModal';
const sectors=[
{id:'fintech',icon:Landmark,name:'Fintech & Banking',signal:'42%',label:'faster onboarding',copy:'Secure digital journeys, intelligent risk systems and data platforms that turn complexity into confidence.',tags:['Digital banking','Risk intelligence','Payment systems']},
{id:'healthcare',icon:HeartPulse,name:'Healthcare',signal:'3.2×',label:'workflow efficiency',copy:'Connected care experiences and automation that give clinical teams more time for the work that matters.',tags:['Patient platforms','Clinical automation','Health data']},
{id:'commerce',icon:ShoppingBag,name:'Retail & Commerce',signal:'+28%',label:'conversion uplift',copy:'Composable commerce, customer intelligence and operational systems built for fast-changing demand.',tags:['Commerce platforms','Personalization','Supply intelligence']},
{id:'enterprise',icon:Factory,name:'Enterprise',signal:'60%',label:'less manual work',copy:'Modern platforms and AI workflows that remove friction across teams, decisions and operations.',tags:['Workflow AI','Legacy modernization','Data foundations']},
{id:'travel',icon:Plane,name:'Travel & Hospitality',signal:'99.9%',label:'platform availability',copy:'Resilient guest platforms and intelligent operations designed for always-on global experiences.',tags:['Guest experience','Revenue systems','Cloud operations']},
{id:'public',icon:Building2,name:'Public Sector',signal:'24/7',label:'citizen access',copy:'Accessible digital public services with the security, transparency and reliability communities expect.',tags:['Citizen portals','Case management','Secure cloud']},
{id:'startups',icon:Rocket,name:'Startups & Scaleups',signal:'4×',label:'faster validation',copy:'Senior product and engineering support to move from a sharp thesis to a dependable, scalable product.',tags:['Product discovery','MVP engineering','Scale architecture']},
{id:'professional',icon:Users,name:'Professional Services',signal:'35%',label:'capacity unlocked',copy:'Knowledge systems and intelligent operations that amplify expert teams without compromising quality.',tags:['Knowledge AI','Client portals','Process automation']}];
const principles=[[ShieldCheck,'Context before technology','We learn the operating model, constraints and economics before defining a solution.'],[Sparkles,'Intelligence with a job','Every AI capability has a measurable purpose, accountable owner and safe operating boundary.'],[TrendingUp,'Outcomes built in','Success metrics shape the roadmap from the first workshop through continuous improvement.']];
export default function WhoWeHelp(){const[open,setOpen]=useState(false);return <main className="industries-page"><Navbar onOpenContact={()=>setOpen(true)}/><section className="industries-hero"><div><p>WHO WE HELP / INDUSTRY INTELLIGENCE</p><h1>Built around your<br/><em>real world.</em></h1><span>Technology performs differently when it understands the environment around it. We combine sector context, product thinking and applied AI to solve the problems that move your business.</span><button onClick={()=>setOpen(true)}>Discuss your challenge <ArrowRight/></button></div><aside><small>SECTORS IN MOTION</small><div className="sector-radar"><i/><i/><i/><b>8</b><span>INDUSTRIES<br/>ONE STANDARD</span></div><footer><span><i/> Systems online</span><b>GLOBAL DELIVERY</b></footer></aside></section><section className="industry-tape"><div>{[...sectors,...sectors].map((s,i)=><span key={`${s.id}-${i}`}>{s.name}<i/></span>)}</div></section><section className="sector-section"><header><div><p>SECTOR EXPERTISE / 01</p><h2>Deep context.<br/>Sharper solutions.</h2></div><span>Every engagement starts with the business reality—not a predetermined stack.</span></header><div className="sector-grid">{sectors.map(({id,icon:Icon,name,signal,label,copy,tags},i)=><article id={id} key={id}><header><small>{String(i+1).padStart(2,'0')}</small><Icon/></header><h3>{name}</h3><p>{copy}</p><div>{tags.map(tag=><span key={tag}>{tag}</span>)}</div><footer><b>{signal}</b><span>{label}</span><button onClick={()=>setOpen(true)} aria-label={`Start a ${name} project`}><ArrowRight/></button></footer></article>)}</div></section><section className="industry-principles"><header><p>HOW WE THINK / 02</p><h2>Industry fluency.<br/><em>Engineering discipline.</em></h2></header><div>{principles.map(([Icon,title,copy],i)=><article key={title}><small>0{i+1}</small><Icon/><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="industry-cta"><div><p>YOUR INDUSTRY. YOUR NEXT ADVANTAGE.</p><h2>Bring us the pressure point.</h2><span>We’ll bring the product, engineering and AI expertise to turn it into forward motion.</span></div><button onClick={()=>setOpen(true)}>Start a project <ArrowRight/></button></section><Footer/><ContactModal isOpen={open} onClose={()=>setOpen(false)}/></main>}
