export const wronyxKnowledge=[
 {id:'leadership',title:'Founder & CEO',url:'/about',text:'Wareesha Ashraf is the Founder and CEO of WRONYX. She is a Full Stack Developer and AI Engineer. Email: wareeshaashraf09@gmail.com. Phone: +92 311 7714594. Portfolio: https://wareeshaportfolio.netlify.app/. GitHub: https://github.com/wareeshayy. LinkedIn: https://www.linkedin.com/in/wareesha-ashraf-17a99827b/.'},
 {id:'company',title:'About WRONYX',url:'/about',text:'WRONYX is a digital innovation and AI product engineering company. It helps ambitious organizations turn ideas into intelligent products, scalable platforms, cloud systems, and measurable digital outcomes.'},
 {id:'services',title:'Services',url:'/services',text:'WRONYX services include AI and intelligent automation, digital product engineering, custom web and mobile development, cloud modernization, data and analytics, cybersecurity, quality engineering, experience design, and dedicated engineering teams.'},
 {id:'ai',title:'AI Engineering',url:'/services',text:'WRONYX designs production-grade AI agents, LLM and retrieval augmented generation systems, intelligent workflows, enterprise knowledge experiences, evaluation frameworks, and responsible AI integrations.'},
 {id:'delivery',title:'How WRONYX Works',url:'/work',text:'WRONYX uses senior specialists, transparent milestone-based delivery, outcome-focused roadmaps, security-first architecture, and close collaboration from discovery through launch and ongoing optimization.'},
 {id:'careers',title:'Careers',url:'/careers',text:'WRONYX is hiring thoughtful builders. Current roles include Senior AI Engineer in Lahore, Frontend Engineer, Cloud Platform Lead, and Senior Product Designer. Candidates can search roles and apply online with browser autofill and résumé upload.'},
 {id:'senior-ai',title:'Senior AI Engineer',url:'/careers/senior-ai-engineer',text:'The Senior AI Engineer role is full-time and on-site in Lahore, Pakistan. It requires production AI and machine learning experience, Python or related languages, PyTorch TensorFlow or scikit-learn, cloud platforms, data pipelines, and strong communication.'},
 {id:'contact',title:'Start a Project',url:'/#contact',text:'To start a project, open the Start a project or Let’s Talk Business form. Share your name, work email, company, project stage, problem, budget range, and timeline. The WRONYX team reviews the brief and responds with a focused next step.'},
];
